# Generated by Django 4.2 on 2023-05-01 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('jersey_no', models.PositiveSmallIntegerField()),
                ('dob', models.DateField()),
                ('position', models.CharField(choices=[('G', 'Goalkeeper'), ('D', 'Defender'), ('M', 'Midfielder'), ('F', 'Forward')], max_length=1)),
                ('goals', models.IntegerField(default=0, null=True)),
                ('assists', models.IntegerField(default=0, null=True)),
                ('yellow_cards', models.IntegerField(default=0, null=True)),
                ('red_cards', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('team_code', models.CharField(max_length=3)),
                ('home_stadium', models.IntegerField()),
                ('goals_scored', models.IntegerField()),
                ('goals_conceded', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('transfer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('transfer_date', models.DateField()),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.player')),
                ('team_from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_from', to='main.teams')),
                ('team_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_to', to='main.teams')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teams'),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score_1', models.PositiveSmallIntegerField(default=0)),
                ('score_2', models.PositiveSmallIntegerField(default=0)),
                ('match_time', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('stadium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stadium')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='main.teams')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='main.teams')),
            ],
        ),
    ]
