# Generated by Django 4.2 on 2023-05-01 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('mgr', 'Manager'), ('ch', 'Coach')], max_length=20)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_id', models.IntegerField()),
                ('match_time', models.DateTimeField()),
                ('assist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='main.player')),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.matches')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='main.player')),
                ('team_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teams')),
            ],
        ),
    ]
