# Generated by Django 4.2 on 2023-05-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_player_nationality"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="assist",
            new_name="assister",
        ),
        migrations.AddField(
            model_name="player",
            name="height",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
