# Generated by Django 4.2 on 2023-05-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_assist_goal_assister_player_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="draws",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="losses",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team",
            name="wins",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="goals_conceded",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="goals_scored",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="team",
            name="points",
            field=models.SmallIntegerField(default=0),
        ),
    ]
