# Generated by Django 4.2 on 2023-05-02 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_team_draws_team_losses_team_wins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="match_time",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MaxLengthValidator(120)]
            ),
        ),
    ]
