# Generated by Django 4.2 on 2023-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_goal_match_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="played",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
