# Generated by Django 4.2 on 2023-05-03 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_team_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="goals_conceded",
            new_name="goals_against",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="goals_scored",
            new_name="goals_for",
        ),
    ]
