# Generated by Django 4.2 on 2023-05-18 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_goals_conceded_team_goals_against_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='match_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)]),
        ),
    ]
